// Generated by https://quicktype.io

import type { MetaData } from "./meta-data";
import type { Event } from "./event";

// Generated by https://quicktype.io

export interface ApiError {
    meta: {
        status: string;
    };
    data: {
        errors: {
            code:    string; // "auth_fail"
            message: string;
        }[];
    };
}

export interface EventsResponse {
    meta: MetaData;
    data: {
        city:   City;
        events: Event[];
    };
}

export interface City {
    id:           number;
    city:         string;
    lat:          number;
    lon:          number;
    state:        string;
    country:      string;
    zip:          string;
    member_count: number;
}

export interface Group {
    created:            number;
    name:               string;
    id:                 number;
    join_mode:          "approval" | "open" | "closed";
    lat:                number;
    lon:                number;
    urlname:            string;
    who:                string;
    localized_location: string;
    state:              string;
    country:            string;
    region:             string;
    timezone:           string;
    category:           GroupCategory;
    photo?:             Photo;
}

export interface GroupCategory {
    id:        number;
    name:      string;
    shortname: string;
    sort_name: string;
}

export interface Photo {
    id:           number;
    highres_link: string;
    photo_link:   string;
    thumb_link:   string;
    type:         "event" | "member";
    base_url:     string;
}

export interface Venue {
    id:                     number;
    name:                   string;
    repinned:               boolean;
    country:                string;
    localized_country_name: string;
    lat?:                   number;
    lon?:                   number;
    address_1?:             string;
    city?:                  string;
    zip?:                   string;
    state?:                 string;
    phone?:                 string;
}


